- group_config:

    - testgroup-tags:

       - name: Test group for tag management
         isMemberOf: 
         members: 
         path: t

- ace_config:

    - testgroup-tags:

       - path: /etc/tags
         permission: allow
         actions: read
         privileges: 
